<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Authors>Björkman, Gus</Authors>
        <Version>0.0.0-localbuild</Version>
        <RepositoryUrl>https://github.com/gus-bjorkman-cg/AdoGen</RepositoryUrl>
        <PackageProjectUrl>https://github.com/gus-bjorkman-cg/AdoGen</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>
</Project>