using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using AdoGen.Generator.Diagnostics;
using AdoGen.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.SqlServer;

internal sealed class BulkEmitterSqlServer : IEmitter
{
    private BulkEmitterSqlServer() {}
    public static BulkEmitterSqlServer Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider) => 
        provider is SqlProviderKind.SqlServer && kind >= SqlModelKind.Bulk;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto, EmitContext ctx)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        var dtoProps = profileInfo.DtoProperties;

        var ns = profileInfo.Namespace;
        var dtoTypeName = dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var tempTableName = $"#AdoGen_{dto.Name}";
        var bulkTypeName = dto.Name + "Bulk";

        if (ctx.Keys.Length == 0)
        {
            spc.ReportDiagnostic(Diagnostic.Create(SqlDiagnostics.MissingKey,
                dto.Locations.FirstOrDefault() ?? Location.None, dto.Name));
            return;
        }

        var joinOn = ctx.JoinOn;
        var idxCols = BuildJoined(ctx.Keys, col => col.ColumnNameQuoted);
        var idxClause =
            $"        CREATE INDEX [IX_AdoGen_{profileInfo.Table}_Op_Key] ON {tempTableName} ([Operation], {idxCols});";

        var insertCols = ctx.NonIdentities.Select(col => col.ColumnNameQuoted).ToArray();
        var insertSelect = ctx.NonIdentities.Select(col => $"S.{col.ColumnNameQuoted}").ToArray();
        var updateSet = string.Join(",\n        ", ctx.NonKeyNonIdentities
            .Select(col => $"    T.{col.ColumnNameQuoted} = S.{col.ColumnNameQuoted}"));

        // CREATE TEMP TABLE (no identity clause; it's just staging)
        var sbColDefs = new StringBuilder();
        for (var i = 0; i < ctx.Columns.Length; i++)
        {
            var col = ctx.Columns[i];
            var nullability = col.IsNullable ? "NULL" : "NOT NULL";
            sbColDefs.AppendLine($"            {col.ColumnNameQuoted} {col.SqlType} {nullability},");
        }
        sbColDefs.Append("            [Operation] CHAR(1) NOT NULL");
        var colDefs = sbColDefs.ToString();

        var tempTableSql =
            $"""
             CREATE TABLE {tempTableName}(
             {colDefs});
             """;

        var schemaTable = ctx.SchemaTableQuoted;
        var applySql = BuildApplySql();
        var typeKeyword = dto.IsRecord ? "record" : "class";
        var accessibility = dto.DeclaredAccessibility.ToString().ToLowerInvariant();

        // Generated file
        var src =
            $$$""""
               // <auto-generated />
               #nullable enable
               using System;
               using System.Data;
               using System.Collections.Generic;
               using System.Threading;
               using System.Threading.Tasks;
               using Microsoft.Data.SqlClient;
               using AdoGen.SqlServer;

               namespace {{{ns}}};

               {{{accessibility}}} sealed partial {{{typeKeyword}}} {{{dto.Name}}} : ISqlBulkModel<{{{dtoTypeName}}}>;

               {{{accessibility}}} sealed class {{{bulkTypeName}}} : BulkBatchSql<{{{dtoTypeName}}}>
               {
                   private const string _tempTableName = "{{{tempTableName}}}";

                   private const string _sqlCreateTempTable =
                       """
                       {{{tempTableSql}}}
                       """;

                   private const string _sqlApply =
                       """
                       {{{applySql}}}
                       """;

                   protected override string SqlCreateTempTable => _sqlCreateTempTable;
                   protected override string TempTableName => _tempTableName;
                   protected override string SqlApply => _sqlApply;
                   protected override int FieldCount => {{{dtoProps.Length + 1}}};

                   /// <summary>
                   /// Initializes a new instance of the BulkBatch class with an optional initial capacity for
                   /// the items and operations lists.
                   /// </summary>
                   /// <param name="capacity"></param>
                   public {{{bulkTypeName}}}(int capacity = 0) : base(capacity) { }

                   protected override async ValueTask WriteItemsToServerAsync(SqlBulkCopy bulk, CancellationToken ct)
                   {
                       using var reader = new __BulkReader(this);
                       await bulk.WriteToServerAsync(reader, ct).ConfigureAwait(false);
                   }
                   
                   protected override void ApplyColumnMappings(SqlBulkCopy bulk)
                   {
               {{{BulkCopyMappings()}}}
                   }

                   private sealed class __BulkReader : AdoGen.SqlServer.BulkDataReaderBase
                   {
                       private readonly AdoGen.SqlServer.BulkBatchSql<{{{dtoTypeName}}}> _batch;
                       private int _index = -1;
                       private {{{dtoTypeName}}} _item = null!;
                       private char _op;

                       public __BulkReader(AdoGen.SqlServer.BulkBatchSql<{{{dtoTypeName}}}> batch) => _batch = batch;

                       public override bool Read() 
                       {
                           ++_index;
                           if (_index >= _batch.Items.Count) return false;
                           
                           _item = _batch.Items[_index];
                           _op = _batch.Operations[_index].Value;
                           return true;
                       }
                        
                       public override int FieldCount => {{{dtoProps.Length + 1}}};

                       public override object GetValue(int i) => i switch
                       {
               {{{GetValueSwitch()}}}
                           {{{dtoProps.Length}}} => _op,
                           _ => throw new IndexOutOfRangeException()
                       };

                       public override string GetName(int i) => i switch
                       {
               {{{GetNameSwitch()}}}
                           {{{dtoProps.Length}}} => "Operation",
                           _ => throw new IndexOutOfRangeException()
                       };

                       public override Type GetFieldType(int i) => i switch
                       {
               {{{GetTypeSwitch()}}}
                           {{{dtoProps.Length}}} => typeof(char),
                           _ => throw new IndexOutOfRangeException()
                       };

                       public override int GetOrdinal(string name) => name switch
                       {
               {{{GetOrdinalSwitch()}}}
                           _ => -1
                       };
                   }
               }
               """";

        spc.AddSource($"{dto.Name}.Bulk.Sql.g.cs", src);
        return;

        string BuildApplySql()
        {
            var sb = new StringBuilder();

            sb.AppendLine("BEGIN TRY");
            sb.AppendLine("        DECLARE @inserted INT = 0, @updated INT = 0, @deleted INT = 0;");
            sb.AppendLine(idxClause);
            sb.AppendLine();

            if (ctx.NonKeyNonIdentities.Length > 0)
            {
                sb.AppendLine("        UPDATE T");
                sb.AppendLine("        SET");
                sb.AppendLine("        " + updateSet);
                sb.AppendLine($"        FROM {schemaTable} AS T");
                sb.AppendLine($"            JOIN {tempTableName} AS S ON {joinOn}");
                sb.AppendLine("        WHERE S.[Operation] = 'U';");
                sb.AppendLine("        SET @updated = @@ROWCOUNT;");
                sb.AppendLine();
            }

            if (insertCols.Length > 0)
            {
                sb.AppendLine($"        INSERT INTO {schemaTable} ({string.Join(", ", insertCols)})");
                sb.AppendLine($"        SELECT {string.Join(", ", insertSelect)}");
                sb.AppendLine($"        FROM {tempTableName} AS S");
                sb.AppendLine("        WHERE S.[Operation] = 'I';");
                sb.AppendLine("        SET @inserted = @@ROWCOUNT;");
                sb.AppendLine();
            }

            sb.AppendLine("        DELETE T");
            sb.AppendLine($"        FROM {schemaTable} AS T");
            sb.AppendLine($"            JOIN {tempTableName} AS S ON {joinOn}");
            sb.AppendLine("        WHERE S.[Operation] = 'D';");
            sb.AppendLine("        SET @deleted = @@ROWCOUNT;");
            sb.AppendLine();
            sb.AppendLine("        SELECT @inserted AS Inserted, @updated AS Updated, @deleted AS Deleted;");
            sb.AppendLine();
            sb.AppendLine("        END TRY");
            sb.AppendLine("        BEGIN CATCH");
            sb.AppendLine($"    {DropGuard(tempTableName)}");
            sb.AppendLine("            THROW;");
            sb.AppendLine("        END CATCH;");
            sb.AppendLine(DropGuard(tempTableName));

            return sb.ToString().TrimEnd();

            static string DropGuard(string name)
                => $"        IF OBJECT_ID('tempdb..{name}') IS NOT NULL DROP TABLE {name};";
        }

        string BulkCopyMappings()
        {
            var sb = new StringBuilder();
            foreach (var col in ctx.Columns)
                sb.AppendLine($"        bulk.ColumnMappings.Add(\"{col.ParameterName}\", \"{col.ParameterName}\");");
            return sb.ToString().TrimEnd();
        }

        string GetNameSwitch()
        {
            var sb = new StringBuilder();
            for (var i = 0; i < ctx.Columns.Length; i++)
                sb.AppendLine($"            {i} => \"{ctx.Columns[i].ParameterName}\",");
            return sb.ToString().TrimEnd();
        }

        string GetTypeSwitch()
        {
            var sb = new StringBuilder();
            for (var i = 0; i < dtoProps.Length; i++)
            {
                var p = dtoProps[i];
                var t = GetUnderlyingTypeSymbol(p.Type);
                var typeName = t.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat).TrimEnd('?');
                sb.AppendLine($"            {i} => typeof({typeName}),");
            }
            return sb.ToString().TrimEnd();
        }

        string GetValueSwitch()
        {
            var sb = new StringBuilder();
            for (var i = 0; i < dtoProps.Length; i++)
            {
                var p = dtoProps[i];
                var col = ctx.Columns[i];
                var expr = GetValueExpression(p, col.IsNullable);
                sb.AppendLine($"            {i} => {expr},");
            }
            return sb.ToString().TrimEnd();
        }

        static ITypeSymbol GetUnderlyingTypeSymbol(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol nts &&
                nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T &&
                nts.TypeArguments.Length == 1)
            {
                return nts.TypeArguments[0];
            }
            return type;
        }

        string GetValueExpression(IPropertySymbol p, bool isNullable)
        {
            if (isNullable && p.Type.IsReferenceType)
                return $"_item.{p.Name} ?? (object)DBNull.Value";

            if (isNullable && p.Type is INamedTypeSymbol nts &&
                nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                return $"_item.{p.Name}.HasValue ? _item.{p.Name}.Value : DBNull.Value";

            return $"_item.{p.Name}";
        }

        string GetOrdinalSwitch()
        {
            var sb = new StringBuilder();
            for (var i = 0; i < ctx.Columns.Length; i++)
                sb.AppendLine($"            \"{ctx.Columns[i].ParameterName}\" => {i},");
            sb.AppendLine($"            \"Operation\" => {ctx.Columns.Length},");
            return sb.ToString().TrimEnd();
        }
    }

    private static string BuildJoined(ImmutableArray<ColumnInfo> columns, Func<ColumnInfo, string> selector)
    {
        if (columns.Length == 0) return string.Empty;
        if (columns.Length == 1) return selector(columns[0]);
        var sb = new StringBuilder(capacity: columns.Length * 24);
        for (var i = 0; i < columns.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(selector(columns[i]));
        }
        return sb.ToString();
    }
}
