using System.Linq;
using System.Text;
using AdoGen.Generator.Diagnostics;
using AdoGen.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.SqlServer;

internal sealed class BulkEmitterSqlServer : IEmitter
{
    private BulkEmitterSqlServer() {}
    public static BulkEmitterSqlServer Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider) => 
        provider is SqlProviderKind.SqlServer && kind >= SqlModelKind.Bulk;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto, EmitContext ctx)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        var dtoProps = profileInfo.DtoProperties;

        var ns = profileInfo.Namespace;
        var dtoTypeName = dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var tempTableName = $"#AdoGen_{dto.Name}";
        var bulkTypeName = dto.Name + "Bulk";

        if (ctx.Keys.Length == 0)
        {
            spc.ReportDiagnostic(Diagnostic.Create(SqlDiagnostics.MissingKey,
                dto.Locations.FirstOrDefault() ?? Location.None, dto.Name));
            return;
        }

        var bulkColumns = ctx.BulkColumns;
        var bulkFieldCount = bulkColumns.Length;

        // SQL strings — produced by SqlServerSqlTextBuilder
        var tempTableSql = SqlServerSqlTextBuilder.BulkCreateTempTable(ctx, tempTableName);
        var applyOptions = new BulkApplyOptions(
            HasInserts: ctx.Writables.Length > 0,
            HasUpdates: ctx.WritableNonKeyNonIdentities.Length > 0);
        var applySql = SqlServerSqlTextBuilder.BulkApply(ctx, tempTableName, applyOptions);
        var createIndexSql = SqlServerSqlTextBuilder.BulkCreateIndex(ctx, tempTableName);
        var typeKeyword = dto.IsRecord ? "record" : "class";
        var accessibility = dto.DeclaredAccessibility.ToString().ToLowerInvariant();

        // Generated file
        var src =
            $$$""""
               // <auto-generated />
               #nullable enable
               using System;
               using System.Data;
               using System.Collections.Generic;
               using System.Threading;
               using System.Threading.Tasks;
               using Microsoft.Data.SqlClient;
               using AdoGen.SqlServer;

               namespace {{{ns}}};

               {{{accessibility}}} sealed partial {{{typeKeyword}}} {{{dto.Name}}} : ISqlBulkModel<{{{dtoTypeName}}}>;

               {{{accessibility}}} sealed class {{{bulkTypeName}}} : BulkBatchSql<{{{dtoTypeName}}}>
               {
                   private const string _tempTableName = "{{{tempTableName}}}";

                   private const string _sqlCreateTempTable =
                       """
                       {{{tempTableSql}}}
                       """;

                   private const string _sqlApply =
                       """
                       {{{applySql}}}
                       """;

                   private const string _sqlApplyWithIndex = """{{{createIndexSql}}}""" + "\n" + _sqlApply;

                   protected override string SqlCreateTempTable => _sqlCreateTempTable;
                   protected override string TempTableName => _tempTableName;
                   protected override string SqlApply => _sqlApply;
                   protected override string SqlApplyWithIndex => _sqlApplyWithIndex;
                   protected override int FieldCount => {{{bulkFieldCount + 1}}};

                    /// <summary>
                    /// Initializes a new instance of the BulkBatch class with an optional initial capacity for
                    /// the items and operations lists.
                    /// </summary>
                    /// <param name="capacity"></param>
                    public {{{bulkTypeName}}}(int capacity = 0) : base(capacity) { }

                    protected override async ValueTask WriteItemsToServerAsync(SqlBulkCopy bulk, CancellationToken ct)
                    {
                        using var reader = new __BulkReader(this);
                        await bulk.WriteToServerAsync(reader, ct).ConfigureAwait(false);
                    }
                    
                    protected override void ApplyColumnMappings(SqlBulkCopy bulk)
                    {
               {{{BulkCopyMappings()}}}
                    }

                    private sealed class __BulkReader : AdoGen.SqlServer.BulkDataReaderBase
                    {
                        private readonly AdoGen.SqlServer.BulkBatchSql<{{{dtoTypeName}}}> _batch;
                        private int _index = -1;
                        private {{{dtoTypeName}}} _item = null!;
                        private char _op;

                        public __BulkReader(AdoGen.SqlServer.BulkBatchSql<{{{dtoTypeName}}}> batch) => _batch = batch;

                        public override bool Read() 
                        {
                            ++_index;
                            if (_index >= _batch.Items.Count) return false;
                            
                            _item = _batch.Items[_index];
                            _op = _batch.Operations[_index].Value;
                            return true;
                        }
                         
                        public override int FieldCount => {{{bulkFieldCount + 1}}};

                        public override object GetValue(int i) => i switch
                        {
               {{{GetValueSwitch()}}}
                            {{{bulkFieldCount}}} => _op,
                            _ => throw new IndexOutOfRangeException()
                        };

                        public override string GetName(int i) => i switch
                        {
               {{{GetNameSwitch()}}}
                            {{{bulkFieldCount}}} => "Operation",
                            _ => throw new IndexOutOfRangeException()
                        };

                        public override Type GetFieldType(int i) => i switch
                        {
               {{{GetTypeSwitch()}}}
                            {{{bulkFieldCount}}} => typeof(char),
                            _ => throw new IndexOutOfRangeException()
                        };

                        public override int GetOrdinal(string name) => name switch
                        {
               {{{GetOrdinalSwitch()}}}
                            _ => -1
                        };
                    }
                }
               """";

        spc.AddSource($"{dto.Name}.Bulk.Sql.g.cs", src);
        
        return;


        string BulkCopyMappings()
        {
            var sb = new StringBuilder();
            
            foreach (var col in bulkColumns)
                sb.AppendLine($"         bulk.ColumnMappings.Add(\"{col.ParameterName}\", \"{col.ParameterName}\");");
            
            return sb.ToString().TrimEnd();
        }

        string GetNameSwitch()
        {
            var sb = new StringBuilder();
            
            for (var i = 0; i < bulkColumns.Length; i++)
                sb.AppendLine($"             {i} => \"{bulkColumns[i].ParameterName}\",");
            
            return sb.ToString().TrimEnd();
        }

        string GetTypeSwitch()
        {
            var sb = new StringBuilder();
            for (var i = 0; i < bulkColumns.Length; i++)
            {
                IPropertySymbol? p = null;
                for (var j = 0; j < dtoProps.Length; j++)
                    if (dtoProps[j].Name == bulkColumns[i].Name) { p = dtoProps[j]; break; }
                if (p is null) continue;
                var t = GetUnderlyingTypeSymbol(p.Type);
                var typeName = t.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat).TrimEnd('?');
                sb.AppendLine($"             {i} => typeof({typeName}),");
            }
            
            return sb.ToString().TrimEnd();
        }

        string GetValueSwitch()
        {
            var sb = new StringBuilder();
            for (var i = 0; i < bulkColumns.Length; i++)
            {
                var col = bulkColumns[i];
                IPropertySymbol? p = null;
                
                for (var j = 0; j < dtoProps.Length; j++)
                    if (dtoProps[j].Name == col.Name) { p = dtoProps[j]; break; }
                
                if (p is null) continue;
                
                var expr = GetValueExpression(p, col.IsNullable);
                sb.AppendLine($"             {i} => {expr},");
            }
            
            return sb.ToString().TrimEnd();
        }

        static ITypeSymbol GetUnderlyingTypeSymbol(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol nts &&
                nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T &&
                nts.TypeArguments.Length == 1)
            {
                return nts.TypeArguments[0];
            }
            
            return type;
        }

        string GetValueExpression(IPropertySymbol p, bool isNullable)
        {
            if (isNullable && p.Type.IsReferenceType)
                return $"_item.{p.Name} ?? (object)DBNull.Value";

            if (isNullable && p.Type is INamedTypeSymbol nts &&
                nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                return $"_item.{p.Name}.HasValue ? _item.{p.Name}.Value : DBNull.Value";

            return $"_item.{p.Name}";
        }

        string GetOrdinalSwitch()
        {
            var sb = new StringBuilder();
            
            for (var i = 0; i < bulkColumns.Length; i++)
                sb.AppendLine($"             \"{bulkColumns[i].ParameterName}\" => {i},");
            
            sb.AppendLine($"             \"Operation\" => {bulkColumns.Length},");
            
            return sb.ToString().TrimEnd();
        }
    }
}
