using System.Linq;
using System.Text;
using AdoGen.Generator.Extensions;
using AdoGen.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.SqlServer;

internal sealed class DtoMapperEmitterSqlServer : IEmitter
{
    private DtoMapperEmitterSqlServer() {}
    public static DtoMapperEmitterSqlServer Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider) =>
        provider is SqlProviderKind.SqlServer && kind >= SqlModelKind.Mapper;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        var accessibility = dto.DeclaredAccessibility.ToString().ToLowerInvariant();
        var setUsingConstructor = dto.Constructors.Any(x => x.Parameters.Length > 0);

        var ordinals = new StringBuilder();
        var init = new StringBuilder();
        var read = new StringBuilder();
        var constBuilder = new StringBuilder();
        var methodBuilder = new StringBuilder();
        var sep = setUsingConstructor ? ":" : "=";
        var needsEnumCastHelper = false;

        if (setUsingConstructor) read.Append('(').AppendLine();
        else read.AppendLine("{");

        for (var i = 0; i < profileInfo.DtoProperties.Length; i++)
        {
            var p = profileInfo.DtoProperties[i];
            var cfg = profileInfo.ParamsByProperty[p.Name];
            var ordinalField = $"{cfg.ParameterName}Ordinal";
            var isLast = i == profileInfo.DtoProperties.Length - 1;
            var getterExpr = EmitReaderGet(p, ordinalField, out bool needsEnumCastForThis);

            if (needsEnumCastForThis) needsEnumCastHelper = true;
            
            ordinals.AppendLine($"    private static int {ordinalField};");
            init.AppendLine($"            {ordinalField} = reader.GetOrdinal(\"{cfg.ParameterName}\");");
            read.AppendLine($"            {cfg.PropertyName} {sep} {getterExpr}{(isLast ? "" : ",")}");
            constBuilder.AppendLine(CreateSqlParameterConst(cfg));
            methodBuilder.AppendLine(CreateSqlParameterMethod(cfg));
        }

        read.Append(setUsingConstructor ? "        )" : "        }");

        var methods = methodBuilder.ToString().TrimEnd();
        var dtoTypeName = dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var typeKeyword = dto.IsRecord ? "record" : "class";
        var ns = profileInfo.Namespace;
        var castHelper = needsEnumCastHelper ? EnumHelper : "";
        var isInitField = "IsInitialized";

        var src = 
            $$"""
            // <auto-generated />
            #nullable enable
            using AdoGen.SqlServer;
            using Microsoft.Data.SqlClient;
            using System;
            using System.Data;
            using System.Runtime.CompilerServices;

            namespace {{ns}};

            {{accessibility}} sealed partial {{typeKeyword}} {{dto.Name}} : ISqlMapper<{{dtoTypeName}}>
            {
                private static bool {{isInitField}};
            {{ordinals}}
                public static {{dtoTypeName}} Map(SqlDataReader reader)
                {
                    if (!{{isInitField}})
                    {
            {{init}}
                        {{isInitField}} = true;
                    }

                    return new {{dtoTypeName}}{{read}};
                }{{castHelper}}
            }
            
            /// <summary>
            /// Helper methods for creating typed SQL parameters for {{dto.Name}}.
            /// </summary>
            {{accessibility}} static class {{dto.Name}}Sql
            {
            {{constBuilder}}
            {{methods}}
            }
            """;

        spc.AddSource($"{dto.Name}.Mapper.Sql.g.cs", src);
    }

    private const string EnumHelper =
        """
         
             private static TEnum EnumCast<TUnderlying, TEnum>(TUnderlying value)
                 where TUnderlying : unmanaged
                 where TEnum : unmanaged
                 => Unsafe.As<TUnderlying, TEnum>(ref value);
         """;

    private static string EmitReaderGet(
        IPropertySymbol p,
        string ordinalField,
        out bool needsEnumCastHelper)
    {
        var (underlying, isNullableValueType) = p.Type.UnwrapNullable();
        var isNullable = isNullableValueType || p.NullableAnnotation == NullableAnnotation.Annotated;
        var propertyTypeKey = p.Type.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat);
        var dbNullValueExpr = isNullableValueType ? $"({propertyTypeKey})null" : "null";
        
        if (underlying.TypeKind == TypeKind.Enum)
        {
            needsEnumCastHelper = true;
            var enumUnderlying = ((INamedTypeSymbol)underlying).EnumUnderlyingType!;

            var (eu, _) = enumUnderlying.UnwrapNullable();
            var coreGetterName = eu.SpecialType switch
            {
                SpecialType.System_SByte => "GetSByte",
                SpecialType.System_Byte => "GetByte",
                SpecialType.System_Int16 => "GetInt16",
                SpecialType.System_UInt16 => "GetInt16",
                SpecialType.System_Int32 => "GetInt32",
                SpecialType.System_UInt32 => "GetInt32",
                SpecialType.System_Int64 => "GetInt64",
                SpecialType.System_UInt64 => "GetInt64",
                _ => null
            };

            if (coreGetterName is not null)
            {
                var read = $"reader.{coreGetterName}({ordinalField})";
                var cast = $"({underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat)}){read}";
                return isNullable
                    ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {cast}"
                    : cast;
            }

            var enumKey = underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat);
            var fv = $"reader.GetFieldValue<{enumKey}>({ordinalField})";
            return isNullable ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {fv}" : fv;
        }
        
        needsEnumCastHelper = false;
        
        if (underlying.SpecialType == SpecialType.System_Char)
        {
            var readChar = $"reader.GetString({ordinalField})[0]";
            
            return isNullable
                ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {readChar}"
                : readChar;
        }

        var getter = underlying.SpecialType switch
        {
            SpecialType.System_Boolean => "GetBoolean",
            SpecialType.System_Byte => "GetByte",
            SpecialType.System_Int16 => "GetInt16",
            SpecialType.System_Int32 => "GetInt32",
            SpecialType.System_Int64 => "GetInt64",
            SpecialType.System_Single => "GetFloat",
            SpecialType.System_Double => "GetDouble",
            SpecialType.System_Decimal => "GetDecimal",
            SpecialType.System_String => "GetString",
            _ => underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat) switch
            {
                "global::System.Guid" => "GetGuid",
                "global::System.DateTime" => "GetDateTime",
                var key => $"GetFieldValue<{key}>"
            }
        };

        getter = $"reader.{getter}({ordinalField})";

        return isNullable ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {getter}" : getter;
    }
    
    private static string CreateSqlParameterConst(ParamConfig cfg)
        => $"""    public const string Parameter{cfg.PropertyName} = "{cfg.ParameterName}";""";

    private static readonly SymbolDisplayFormat TypeDisplay = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                                  SymbolDisplayMiscellaneousOptions.UseSpecialTypes);
    
    private static string CreateSqlParameterMethod(ParamConfig cfg)
    {
        var methodName = $"CreateParameter{cfg.PropertyName}";
        var constName = $"Parameter{cfg.PropertyName}";
        var typeName = cfg.PropertyType.ToDisplayString(TypeDisplay);

        var isNullableValueType = cfg.PropertyType is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };
        var valueExpr = cfg.PropertyType.IsReferenceType || isNullableValueType ? "value is null ? DBNull.Value : value" : "value";

        var optional = new StringBuilder();
        if (cfg.Size is { } size) optional.AppendLine($"        Size = {size},");
        if (cfg.Precision is { } pr) optional.AppendLine($"        Precision = {pr},");
        if (cfg.Scale is { } sc) optional.AppendLine($"        Scale = {sc},");

        var optionalParams = optional.ToString().TrimEnd();

        return 
            $$"""
                  /// <summary>
                  /// Creates a SqlParameter with the configured db type and size/precision/scale.
                  /// </summary>
                  [MethodImpl(MethodImplOptions.AggressiveInlining)]
                  public static SqlParameter {{methodName}}({{typeName}} value, string? propertyName = null) => new()
                  {
                      ParameterName = propertyName ?? {{constName}},
                      SqlDbType = SqlDbType.{{cfg.DbType!.Value.EnumMember}},
                      Value = {{valueExpr}},{{(string.IsNullOrEmpty(optionalParams) ? "" : "\n" + optionalParams)}}
                  };
                  
              """;
    }
}