using System.Linq;
using System.Text;
using AdoGen.Generator.Models;
using AdoGen.Generator.Pipelines;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.SqlServer;

internal sealed class ParameterHelpersEmitterSqlServer : IEmitter
{
    private ParameterHelpersEmitterSqlServer() {}
    public static ParameterHelpersEmitterSqlServer Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider) =>
        provider is SqlProviderKind.SqlServer && kind >= SqlModelKind.Result;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        
        var constBuilder = new StringBuilder();
        var methodBuilder = new StringBuilder();

        var paramConfigs = profileInfo.ParamsByProperty.Select(x => x.Value).OrderBy(x => x.PropertyName);
        foreach (var kvp in paramConfigs)
        {
            constBuilder.AppendLine(CreateSqlParameterConst(kvp));
            methodBuilder.AppendLine(CreateSqlParameterMethod(kvp));
            methodBuilder.AppendLine();
        }
        
        var methods = methodBuilder.ToString().TrimEnd();

        var src = 
            $$"""
            // <auto-generated />
            #nullable enable
            using System;
            using System.Data;
            using System.Runtime.CompilerServices;
            using Microsoft.Data.SqlClient;

            namespace AdoGen.SqlServer;

            /// <summary>
            /// Helper methods for creating typed SQL parameters for {{dto.Name}}.
            /// </summary>
            public static class {{dto.Name}}Sql
            {
            {{constBuilder}}
            {{methods}}
            }
            """;

        spc.AddSource($"{dto.Name}.Sql.g.cs", src);
    }

    private static readonly SymbolDisplayFormat TypeDisplay = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                                  SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static string CreateSqlParameterConst(ParamConfig cfg)
        => $"""    public const string Parameter{cfg.PropertyName} = "{cfg.ParameterName}";""";

    private static string CreateSqlParameterMethod(ParamConfig cfg)
    {
        var methodName = $"CreateParameter{cfg.PropertyName}";
        var constName = $"Parameter{cfg.PropertyName}";
        var typeName = cfg.PropertyType.ToDisplayString(TypeDisplay);

        var isNullableValueType = cfg.PropertyType is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };
        var valueExpr = cfg.PropertyType.IsReferenceType || isNullableValueType ? "value is null ? DBNull.Value : value" : "value";

        var optional = new StringBuilder();
        if (cfg.Size is { } size) optional.AppendLine($"        Size = {size},");
        if (cfg.Precision is { } pr) optional.AppendLine($"        Precision = {pr},");
        if (cfg.Scale is { } sc) optional.AppendLine($"        Scale = {sc},");

        var optionalParams = optional.ToString().TrimEnd();

        return $$"""
                /// <summary>
                /// Creates a SqlParameter with the configured db type and size/precision/scale.
                /// </summary>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static SqlParameter {{methodName}}({{typeName}} value, string? propertyName = null) => new()
                {
                    ParameterName = propertyName ?? {{constName}},
                    SqlDbType = SqlDbType.{{cfg.DbType!.Value.EnumMember}},
                    Value = {{valueExpr}},{{(string.IsNullOrEmpty(optionalParams) ? "" : "\n" + optionalParams)}}
                };
            """;
    }
}