using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using AdoGen.Generator.Extensions;
using AdoGen.Generator.Pipelines;

namespace AdoGen.Generator.Emitters;

internal static class DtoMapperEmitter
{
    public static void Emit(SourceProductionContext spc, DiscoveryDto discoveryDto)
    {
        var (dto, _, _, _) = discoveryDto;
        
        var props = dto.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(x => x.DeclaredAccessibility == Accessibility.Public)
            .Where(x => !x.IsStatic)
            .OrderBy(x => x.Name, StringComparer.Ordinal)
            .ToArray();

        var setUsingConstructor = dto.Constructors.Any(x => x.Parameters.Length > 0);

        var ordinals = new StringBuilder();
        var init = new StringBuilder();
        var read = new StringBuilder();
        var sep = setUsingConstructor ? ":" : "=";
        var needsEnumCastHelper = false;

        if (setUsingConstructor) read.Append('(').AppendLine();
        else read.AppendLine("{");

        for (var i = 0; i < props.Length; i++)
        {
            var p = props[i];
            var ordinalField = $"{p.Name}Ordinal";
            var isLast = i == props.Length - 1;
            
            var getterExpr = EmitReaderGet(p, ordinalField, out bool needsEnumCastForThis);

            if (needsEnumCastForThis) needsEnumCastHelper = true;
            
            ordinals.AppendLine($"    private static int {ordinalField};");
            init.AppendLine($"            {ordinalField} = reader.GetOrdinal(\"{p.Name}\");");
            read.AppendLine($"            {p.Name} {sep} {getterExpr}{(isLast ? "" : ",")}");
        }

        read.Append(setUsingConstructor ? "        )" : "        }");

        var dtoTypeName = dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var typeKeyword = dto.IsRecord ? "record" : "class";
        var ns = dto.ContainingNamespace.IsGlobalNamespace ? "GlobalNamespace" : dto.ContainingNamespace.ToDisplayString();
        var castHelper = needsEnumCastHelper ? EnumHelper : "";

        var src = $$"""
            // <auto-generated />
            using System.Runtime.CompilerServices;
            using Microsoft.Data.SqlClient;
            using AdoGen.Abstractions;

            namespace {{ns}};

            public sealed partial {{typeKeyword}} {{dto.Name}} : ISqlResult<{{dtoTypeName}}>
            {
                private static bool IsInitialized;
            {{ordinals}}
                public static {{dtoTypeName}} Map(SqlDataReader reader)
                {
                    if (!IsInitialized)
                    {
            {{init}}
                        IsInitialized = true;
                    }

                    return new {{dtoTypeName}}{{read}};
                }{{castHelper}}
            }
            """;

        spc.AddSource($"{dto.Name}Mapper.g.cs", src);
    }

    private const string EnumHelper =
        """
         
             private static TEnum EnumCast<TUnderlying, TEnum>(TUnderlying value)
                 where TUnderlying : unmanaged
                 where TEnum : unmanaged
                 => Unsafe.As<TUnderlying, TEnum>(ref value);
         """;
    
    private static string EmitReaderGet(
        IPropertySymbol p,
        string ordinalField,
        out bool needsEnumCastHelper)
    {
        var (underlying, isNullable) = p.Type.UnwrapNullable();

        if (underlying.TypeKind == TypeKind.Enum)
        {
            needsEnumCastHelper = true; // you can do it inline; no helper needed
            var enumUnderlying = ((INamedTypeSymbol)underlying).EnumUnderlyingType!;

            // Re-enter the same switch using the enum's underlying type
            var (eu, _) = enumUnderlying.UnwrapNullable(); // not nullable in practice
            var coreGetterName = eu.SpecialType switch
            {
                SpecialType.System_SByte => "GetSByte",
                SpecialType.System_Byte => "GetByte",
                SpecialType.System_Int16 => "GetInt16",
                SpecialType.System_UInt16 => "GetInt16",
                SpecialType.System_Int32 => "GetInt32",
                SpecialType.System_UInt32 => "GetInt32",
                SpecialType.System_Int64 => "GetInt64",
                SpecialType.System_UInt64 => "GetInt64",
                _ => null
            };

            if (coreGetterName is not null)
            {
                var read = $"reader.{coreGetterName}({ordinalField})";
                var cast = $"({underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat)}){read}";

                return isNullable
                    ? $"reader.IsDBNull({ordinalField}) ? default : {cast}"
                    : cast;
            }
            
            var enumKey = underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat);
            var fv = $"reader.GetFieldValue<{enumKey}>({ordinalField})";
            return isNullable ? $"reader.IsDBNull({ordinalField}) ? default : {fv}" : fv;
        }

        var getter = underlying.SpecialType switch
        {
            SpecialType.System_Boolean => "GetBoolean",
            SpecialType.System_Byte => "GetByte",
            SpecialType.System_Int16 => "GetInt16",
            SpecialType.System_Int32 => "GetInt32",
            SpecialType.System_Int64 => "GetInt64",
            SpecialType.System_Single => "GetFloat",
            SpecialType.System_Double => "GetDouble",
            SpecialType.System_Decimal => "GetDecimal",
            SpecialType.System_String => "GetString",
            _ => underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat) switch
            {
                "global::System.Guid" => "GetGuid",
                "global::System.DateTime" => "GetDateTime",
                "global::System.DateTimeOffset" => "GetDateTimeOffset",
                var key => $"GetFieldValue<{key}>"
            }
        };
        
        getter = $"reader.{getter}({ordinalField})";
        needsEnumCastHelper = false;
        
        return isNullable ? $"reader.IsDBNull({ordinalField}) ? default : {getter}" : getter;
    }
}
