using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using AdoGen.Generator.Diagnostics;
using AdoGen.Generator.Extensions;
using AdoGen.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.PostgreSql;

internal sealed class BulkEmitterNpgSql : IEmitter
{
    private BulkEmitterNpgSql() { }
    public static BulkEmitterNpgSql Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider)
        => provider is SqlProviderKind.PostgreSql && kind >= SqlModelKind.Bulk;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto, EmitContext ctx)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        var dtoProps = profileInfo.DtoProperties;

        var ns = profileInfo.Namespace;
        var dtoTypeName = dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var tempTableName = $"adoGen_{dto.Name.ToLowerInvariant()}_tmp";
        var bulkTypeName = dto.Name + "NpgsqlBulk";

        if (ctx.Keys.Length == 0)
        {
            spc.ReportDiagnostic(Diagnostic.Create(SqlDiagnostics.MissingKey,
                dto.Locations.FirstOrDefault() ?? Location.None, dto.Name));
            return;
        }
        
        var bulkColumns = ctx.BulkColumns;
        var bulkFieldCount = bulkColumns.Length;
        
        // SQL strings — produced by PostgreSqlSqlTextBuilder
        var tempTableSql = PostgreSqlSqlTextBuilder.BulkCreateTempTable(ctx, tempTableName);
        var createIndexSql = PostgreSqlSqlTextBuilder.BulkCreateIndex(ctx, tempTableName);
        var analyzeSql = PostgreSqlSqlTextBuilder.BulkAnalyze(tempTableName);
        var stmts = PostgreSqlSqlTextBuilder.BulkApply(ctx, tempTableName, ctx.SchemaTableQuoted);
        var typeKeyword = dto.IsRecord ? "record" : "class";
        var accessibility = dto.DeclaredAccessibility.ToString().ToLowerInvariant();

        var copyColumnsEscaped = BuildJoined(bulkColumns, col => $"\"{col.ParameterName}\"") + ", \"operation\"";
        var copyCommand = $"""COPY "{tempTableName}" ({copyColumnsEscaped}) FROM STDIN (FORMAT BINARY)""";

        // Build SQL const declarations as code strings before the template.
        // Using a helper avoids nested raw-string-literal indentation problems
        // and produces clean """ literals in the generated file.
        var sqlConsts = BuildSqlConsts(tempTableSql, createIndexSql, analyzeSql, copyCommand, stmts);

        var src =
            $$$$""""
                // <auto-generated />
                #nullable enable
                using System;
                using System.Data;
                using System.Collections.Generic;
                using System.Threading;
                using System.Threading.Tasks;
                using Npgsql;
                using AdoGen.PostgreSql;

                namespace {{{{ns}}}};

                {{{{accessibility}}}} sealed partial {{{{typeKeyword}}}} {{{{dto.Name}}}} : INpgsqlBulkModel<{{{{dtoTypeName}}}}>;

                {{{{accessibility}}}} sealed class {{{{bulkTypeName}}}} : BulkBatchNpg<{{{{dtoTypeName}}}}>
                {
                    private const string _tempTableName = "{{{{tempTableName}}}}";

                {{{{sqlConsts}}}}

                    protected override string SqlCreateTempTable => _sqlCreateTempTable;
                    protected override string TempTableName => _tempTableName;
                    protected override string SqlCreateIndex => _sqlCreateIndex;
                    protected override string SqlAnalyze => _sqlAnalyze;
                    protected override string? SqlUpdateU => {{{{(stmts.UpdateU is null ? "null" : "_sqlUpdateU")}}}};
                    protected override string? SqlInsertI => {{{{(stmts.InsertI is null ? "null" : "_sqlInsertI")}}}};
                    protected override string SqlDeleteD => _sqlDeleteD;
                    protected override string? SqlUpdateM => {{{{(stmts.UpdateM is null ? "null" : "_sqlUpdateM")}}}};
                    protected override string? SqlInsertM => {{{{(stmts.InsertM is null ? "null" : "_sqlInsertM")}}}};
                    protected override int FieldCount => {{{{bulkFieldCount + 1}}}};

                    public {{{{bulkTypeName}}}}(int capacity = 0) : base(capacity) { }

                    protected override async ValueTask WriteItemsToServerAsync(NpgsqlConnection connection, CancellationToken ct)
                    {
                        await using var importer = connection.BeginBinaryImport(_copyCommand);

                        for (var i = 0; i < Items.Count; i++)
                        {
                            ct.ThrowIfCancellationRequested();

                            var item = Items[i];
                            var op = Operations[i].Value;

                            await importer.StartRowAsync(ct).ConfigureAwait(false);
                {{{{EmitImporterWrites()}}}}
                            importer.Write(op);
                        }

                        await importer.CompleteAsync(ct).ConfigureAwait(false);
                    }
                }
                """";

        spc.AddSource($"{dto.Name}.Bulk.Npgsql.g.cs", src);
        return;

        string EmitImporterWrites()
        {
            var sb = new StringBuilder();
            
            for (var i = 0; i < bulkColumns.Length; i++)
            {
                var col = bulkColumns[i];
                // Find matching dtoProps entry
                IPropertySymbol? p = null;
                for (var j = 0; j < dtoProps.Length; j++)
                {
                    if (dtoProps[j].Name == col.Name) { p = dtoProps[j]; break; }
                }
                
                if (p is null) continue;
                
                var accessor = ResolveNpgsqlBulkWriteAccessor(p);
                sb.AppendLine($"            importer.Write({accessor});");
            }
            
            return sb.ToString().TrimEnd();
        }
    }

    /// <summary>
    /// Builds all SQL const declarations as a pre-formatted code block.
    /// Using a dedicated method avoids nested raw-string-literal indentation problems
    /// inside the outer $$$$"""" template. Each const uses a """ raw string literal —
    /// clean, readable, no double-quote escaping.
    /// </summary>
    private static string BuildSqlConsts(
        string tempTableSql,
        string createIndexSql,
        string analyzeSql,
        string copyCommand,
        BulkApplyStatements stmts)
    {
        const string I = "    "; // 4-space indent for class body members
        var sb = new StringBuilder();

        AppendMultilineConst(sb, I, "_sqlCreateTempTable", tempTableSql);
        sb.AppendLine($"{I}private const string _sqlCreateIndex = \"\"\"{createIndexSql}\"\"\";");
        sb.AppendLine($"{I}private const string _sqlAnalyze = \"\"\"{analyzeSql}\"\"\";");
        sb.AppendLine($"{I}private const string _copyCommand = \"\"\"{copyCommand}\"\"\";");

        if (stmts.UpdateU is not null) AppendMultilineConst(sb, I, "_sqlUpdateU", stmts.UpdateU);
        if (stmts.InsertI is not null) AppendMultilineConst(sb, I, "_sqlInsertI", stmts.InsertI);
        AppendMultilineConst(sb, I, "_sqlDeleteD", stmts.DeleteD);
        if (stmts.UpdateM is not null) AppendMultilineConst(sb, I, "_sqlUpdateM", stmts.UpdateM);
        if (stmts.InsertM is not null) AppendMultilineConst(sb, I, "_sqlInsertM", stmts.InsertM);

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Appends a multiline """ raw string literal const.
    /// Content lines are indented 4 spaces past <paramref name="indent"/> so the
    /// closing """ is the sole dedented line and the raw string rule is satisfied.
    /// </summary>
    private static void AppendMultilineConst(StringBuilder sb, string indent, string name, string content)
    {
        var contentIndent = indent + "    ";
        sb.AppendLine($"{indent}private const string {name} =");
        sb.AppendLine($"{contentIndent}\"\"\"");
        foreach (var rawLine in content.Split('\n'))
        {
            var line = rawLine.TrimEnd('\r');
            sb.AppendLine(line.Length == 0 ? "" : $"{contentIndent}{line}");
        }
        sb.AppendLine($"{contentIndent}\"\"\";");
    }

    private static string BuildJoined(ImmutableArray<ColumnInfo> columns, Func<ColumnInfo, string> selector)    {
        if (columns.Length == 0) return string.Empty;
        if (columns.Length == 1) return selector(columns[0]);
        var sb = new StringBuilder(capacity: columns.Length * 24);
        for (var i = 0; i < columns.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(selector(columns[i]));
        }
        return sb.ToString();
    }

    /// <summary>
    /// Returns the accessor expression for a property in a COPY BINARY write.
    /// Enum values must be cast to their underlying type because Npgsql COPY BINARY
    /// does not support writing .NET enum types directly.
    /// </summary>
    private static string ResolveNpgsqlBulkWriteAccessor(IPropertySymbol p)
    {
        var (underlying, isNullable) = p.Type.UnwrapNullable();
        if (underlying.TypeKind != TypeKind.Enum || underlying is not INamedTypeSymbol enumType)
            return $"item.{p.Name}";

        var castType = enumType.EnumUnderlyingType?.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int32 => "int",
            SpecialType.System_UInt32 => "uint",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            _ => "int"
        };

        return isNullable
            ? $"item.{p.Name}.HasValue ? ({castType})item.{p.Name}.Value : DBNull.Value"
            : $"({castType})item.{p.Name}";
    }
}