using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using AdoGen.Generator.Diagnostics;
using AdoGen.Generator.Extensions;
using AdoGen.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.PostgreSql;

internal sealed class BulkEmitterNpgSql : IEmitter
{
    private BulkEmitterNpgSql() { }
    public static BulkEmitterNpgSql Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider)
        => provider is SqlProviderKind.PostgreSql && kind >= SqlModelKind.Bulk;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto, EmitContext ctx)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        var dtoProps = profileInfo.DtoProperties;

        var ns = profileInfo.Namespace;
        var dtoTypeName = dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var tempTableName = $"adoGen_{dto.Name.ToLowerInvariant()}_tmp";
        var bulkTypeName = dto.Name + "NpgsqlBulk";

        if (ctx.Keys.Length == 0)
        {
            spc.ReportDiagnostic(Diagnostic.Create(SqlDiagnostics.MissingKey,
                dto.Locations.FirstOrDefault() ?? Location.None, dto.Name));
            return;
        }

        var joinOn = ctx.JoinOn;
        var insertCols = BuildJoined(ctx.NonIdentities, col => col.ColumnNameQuoted);
        var insertSelect = BuildJoined(ctx.NonIdentities, col => $"S.{col.ColumnNameQuoted}");
        var updateSet = string.Join(",\n        ", ctx.NonKeyNonIdentities
            .Select(col => $"        \"{col.ParameterName}\" = S.\"{col.ParameterName}\""));

        // CREATE TEMP TABLE
        var sbColDefs = new StringBuilder();
        for (var i = 0; i < ctx.Columns.Length; i++)
        {
            var col = ctx.Columns[i];
            var nullability = col.IsNullable ? "NULL" : "NOT NULL";
            sbColDefs.AppendLine($"""        "{col.ParameterName}" {col.SqlType} {nullability},""");
        }
        sbColDefs.Append("""        "operation" CHAR(1) NOT NULL""");

        var tempTableSql =
            $"""
                 CREATE TEMP TABLE IF NOT EXISTS "{tempTableName}"(
             {sbColDefs});
             """;

        var schemaTable = ctx.SchemaTableQuoted;
        var tempTableRef = $"\"{tempTableName}\"";
        var applySql = BuildApplySql();
        var typeKeyword = dto.IsRecord ? "record" : "class";
        var accessibility = dto.DeclaredAccessibility.ToString().ToLowerInvariant();

        var copyColumnsEscaped = BuildJoined(ctx.Columns, col => $"\"{col.ParameterName}\"") + ", \"operation\"";
        var copyCommand = $"""COPY "{tempTableName}" ({copyColumnsEscaped}) FROM STDIN (FORMAT BINARY)""";

        var src =
            $$$$""""
                // <auto-generated />
                #nullable enable
                using System;
                using System.Data;
                using System.Collections.Generic;
                using System.Threading;
                using System.Threading.Tasks;
                using Npgsql;
                using AdoGen.PostgreSql;

                namespace {{{{ns}}}};

                {{{{accessibility}}}} sealed partial {{{{typeKeyword}}}} {{{{dto.Name}}}} : INpgsqlBulkModel<{{{{dtoTypeName}}}}>;

                {{{{accessibility}}}} sealed class {{{{bulkTypeName}}}} : BulkBatchNpg<{{{{dtoTypeName}}}}>
                {
                    private const string _tempTableName = "{{{{tempTableName}}}}";

                    private const string _sqlCreateTempTable = 
                    """
                {{{{tempTableSql}}}}
                    """;
                    
                    private const string _sqlApply = 
                    """
                {{{{applySql}}}}
                    """;

                    private const string _copyCommand = """{{{{copyCommand}}}}""";

                    protected override string SqlCreateTempTable => _sqlCreateTempTable;
                    protected override string TempTableName => _tempTableName;
                    protected override string SqlApply => _sqlApply;
                    protected override int FieldCount => {{{{dtoProps.Length + 1}}}};

                    public {{{{bulkTypeName}}}}(int capacity = 0) : base(capacity) { }

                    protected override async ValueTask WriteItemsToServerAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, CancellationToken ct)
                    {
                        await using var importer = connection.BeginBinaryImport(_copyCommand);

                        for (var i = 0; i < Items.Count; i++)
                        {
                            ct.ThrowIfCancellationRequested();

                            var item = Items[i];
                            var op = Operations[i].Value;

                            await importer.StartRowAsync(ct).ConfigureAwait(false);
                {{{{EmitImporterWrites()}}}}
                            importer.Write(op);
                        }

                        await importer.CompleteAsync(ct).ConfigureAwait(false);
                    }
                }
                """";

        spc.AddSource($"{dto.Name}.Bulk.Npgsql.g.cs", src);
        return;

        string BuildApplySql()
        {
            var sb = new StringBuilder();
            
            var keyCols = BuildJoined(ctx.Keys, col => $"\"{col.ParameterName}\"");
            var idxCols = $"\"operation\", {keyCols}";
            var idxName = $"ix_{tempTableName}_op_keys";

            sb.AppendLine($"""    CREATE INDEX IF NOT EXISTS "{idxName}" ON {tempTableRef} ({idxCols});""");
            sb.AppendLine();
            
            sb.AppendLine("    WITH updated AS (");
            if (ctx.NonKeyNonIdentities.Length > 0)
            {
                sb.AppendLine($"        UPDATE {schemaTable} AS T");
                sb.AppendLine("            SET " + updateSet.TrimStart());
                sb.AppendLine($"        FROM {tempTableRef} AS S");
                sb.AppendLine($"""        WHERE S."operation" = 'U' AND {joinOn}""");
                sb.AppendLine("        RETURNING 1),");
            }
            else
            {
                sb.AppendLine("        SELECT 1 WHERE false),");
            }
            
            sb.AppendLine("    inserted AS (");
            if (ctx.NonIdentities.Length > 0)
            {
                sb.AppendLine($"        INSERT INTO {schemaTable} ({insertCols})");
                sb.AppendLine($"            SELECT {insertSelect}");
                sb.AppendLine($"            FROM {tempTableRef} AS S");
                sb.AppendLine("            WHERE S.\"operation\" = 'I'");
                sb.AppendLine("        RETURNING 1),");
            }
            else
            {
                sb.AppendLine("        SELECT 1 WHERE false),");
            }
            
            sb.AppendLine("    deleted AS (");
            sb.AppendLine($"        DELETE FROM {schemaTable} AS T");
            sb.AppendLine($"        USING {tempTableRef} AS S");
            sb.AppendLine($"        WHERE S.\"operation\" = 'D' AND {joinOn}");
            sb.AppendLine("        RETURNING 1)");

            sb.AppendLine("    SELECT");
            sb.AppendLine("        (SELECT COUNT(*) FROM inserted) AS Inserted,");
            sb.AppendLine("        (SELECT COUNT(*) FROM updated) AS Updated,");
            sb.AppendLine("        (SELECT COUNT(*) FROM deleted) AS Deleted;");

            return sb.ToString().TrimEnd();
        }
        
        string EmitImporterWrites()
        {
            var sb = new StringBuilder();
            for (var i = 0; i < dtoProps.Length; i++)
            {
                var p = dtoProps[i];
                var accessor = ResolveNpgsqlBulkWriteAccessor(p);
                sb.AppendLine($"            importer.Write({accessor});");
            }
            return sb.ToString().TrimEnd();
        }
    }

    private static string BuildJoined(ImmutableArray<ColumnInfo> columns, Func<ColumnInfo, string> selector)
    {
        if (columns.Length == 0) return string.Empty;
        if (columns.Length == 1) return selector(columns[0]);
        var sb = new StringBuilder(capacity: columns.Length * 24);
        for (var i = 0; i < columns.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(selector(columns[i]));
        }
        return sb.ToString();
    }

    /// <summary>
    /// Returns the accessor expression for a property in a COPY BINARY write.
    /// Enum values must be cast to their underlying type because Npgsql COPY BINARY
    /// does not support writing .NET enum types directly.
    /// </summary>
    private static string ResolveNpgsqlBulkWriteAccessor(IPropertySymbol p)
    {
        var (underlying, isNullable) = p.Type.UnwrapNullable();
        if (underlying.TypeKind != TypeKind.Enum || underlying is not INamedTypeSymbol enumType)
            return $"item.{p.Name}";

        var castType = enumType.EnumUnderlyingType?.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int32 => "int",
            SpecialType.System_UInt32 => "uint",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            _ => "int"
        };

        return isNullable
            ? $"item.{p.Name}.HasValue ? ({castType})item.{p.Name}.Value : DBNull.Value"
            : $"({castType})item.{p.Name}";
    }
}