using System.Text;
using AdoGen.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.PostgreSql;

internal sealed class DomainOpsEmitterNpgSql : IEmitter
{
    private DomainOpsEmitterNpgSql() { }
    public static DomainOpsEmitterNpgSql Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider) =>
        provider is SqlProviderKind.PostgreSql && kind >= SqlModelKind.Domain;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto, EmitContext ctx)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        var typeKeyword = dto.IsRecord ? "record" : "class";

        // SQL strings — produced by PostgreSqlSqlTextBuilder
        var createTableSql = PostgreSqlSqlTextBuilder.CreateTable(ctx);
        var nonIdentityPropCount = ctx.NonIdentities.Length;
        var insertSql = PostgreSqlSqlTextBuilder.Insert(ctx);
        var insertBatchSql = PostgreSqlSqlTextBuilder.InsertBatchPrefix(ctx);
        var updateSql = PostgreSqlSqlTextBuilder.Update(ctx);
        var deleteSql = PostgreSqlSqlTextBuilder.Delete(ctx);
        var upsertSql = PostgreSqlSqlTextBuilder.Upsert(ctx);
        var truncateSql = PostgreSqlSqlTextBuilder.Truncate(ctx);

        var deleteBatchSrc = "";
        if (profileInfo.Keys.Length == 1)
        {
            var keyName = profileInfo.Keys[0];
            var keyType = profileInfo.ParamsByProperty[keyName].PropertyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var deleteBatchSql = PostgreSqlSqlTextBuilder.DeleteBatchTemplate(ctx, keyName);

            deleteBatchSrc =
                $$""""

                  {{ctx.Accessibility}} sealed partial {{typeKeyword}} {{dto.Name}} : INpgsqlSingleIdModel<{{ctx.DtoTypeName}}, {{keyType}}>
                  {
                      private const string Pg_SqlDeleteBatchTemplate = """{{deleteBatchSql}}""";

                      public static async ValueTask<int> DeleteAsync(NpgsqlConnection connection, List<{{keyType}}> ids, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                      {
                          if (ids is null || ids.Count == 0) return 0;
                          if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);

                          var sb = new StringBuilder(Pg_SqlDeleteBatchTemplate);
                          for (var i = 0; i < ids.Count; i++)
                          {
                              if (i > 0) sb.Append(',');
                              sb.Append($"@p{i}");
                          }
                          sb.Append(')');

                          await using var cmd = connection.CreateCommand(sb.ToString(), CommandType.Text, transaction, commandTimeout);

                          for (var i = 0; i < ids.Count; i++)
                          {
                              cmd.Parameters.Add({{dto.Name}}Npgsql.CreateParameter{{keyName}}(ids[i], $"@p{i}"));
                          }

                          return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                      }
                  }

                  """";
        }

        var src =
            $$""""
              // <auto-generated />
              #nullable enable
              using System;
              using System.Data;
              using System.Text;
              using System.Collections.Generic;
              using System.Threading;
              using System.Threading.Tasks;
              using Npgsql;
              using AdoGen.PostgreSql;

              namespace {{ctx.Namespace}};
              {{deleteBatchSrc}}
              {{ctx.Accessibility}} sealed partial {{typeKeyword}} {{dto.Name}} : INpgsqlDomainModel<{{ctx.DtoTypeName}}>
              {
                  private const string Pg_SqlCreateTable = 
                  """
              {{createTableSql}}
                  """;
                  
                  private const string Pg_SqlInsert = """{{insertSql}}""";
                  private const string Pg_SqlInsertBatchTemplate = """{{insertBatchSql}}""";
                  private const string Pg_SqlUpdate = """{{updateSql}}""";
                  private const string Pg_SqlDelete = """{{deleteSql}}""";
                  private const string Pg_SqlTruncate = """{{truncateSql}}""";
                  private const string Pg_SqlUpsert = """{{upsertSql}}""";
                  
                  private const int Pg_NonIdentityPropertyCount = {{nonIdentityPropCount}};

                  public static async ValueTask CreateTableAsync(NpgsqlConnection connection, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                  {
                      if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);
                      await using var cmd = connection.CreateCommand(Pg_SqlCreateTable, CommandType.Text, transaction, commandTimeout);
                      await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                  }

                  public static async ValueTask<int> InsertAsync({{ctx.DtoTypeName}} model, NpgsqlConnection connection, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                  {
                      if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);
                      await using var cmd = connection.CreateCommand(Pg_SqlInsert, CommandType.Text, transaction, commandTimeout);
              {{ParamAdd("model")}}        
                      return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                  }

                  public static async ValueTask<int> InsertAsync(List<{{ctx.DtoTypeName}}> models, NpgsqlConnection connection, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                  {
                      if (models is null || models.Count == 0) return 0;
                      if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);

                      var sb = new StringBuilder(Pg_SqlInsertBatchTemplate);
                      var paramIndex = 0;

                      for (var modelIndex = 0; modelIndex < models.Count; modelIndex++)
                      {
                          if (modelIndex > 0) sb.Append(',');
                          sb.Append('(');
                          for (var columnIndex = 0; columnIndex < Pg_NonIdentityPropertyCount; columnIndex++)
                          {
                              if (columnIndex > 0) sb.Append(',');
                              sb.Append($"@p{paramIndex + columnIndex}");
                          }
                          sb.Append(')');
                          paramIndex += Pg_NonIdentityPropertyCount;
                      }

                      await using var cmd = connection.CreateCommand(sb.ToString(), CommandType.Text, transaction, commandTimeout);
                      paramIndex = 0;

                      foreach (var model in models)
                      {
              {{ParamAddBatchFlat("model", "paramIndex")}}        
                      }

                      return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                  }

                  public static async ValueTask<int> UpdateAsync({{ctx.DtoTypeName}} model, NpgsqlConnection connection, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                  {
                      if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);
                      await using var cmd = connection.CreateCommand(Pg_SqlUpdate, CommandType.Text, transaction, commandTimeout);
              {{ParamAddForUpdate("model")}}        
                      return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                  }

                  public static async ValueTask<int> DeleteAsync({{ctx.DtoTypeName}} model, NpgsqlConnection connection, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                  {
                      if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);
                      await using var cmd = connection.CreateCommand(Pg_SqlDelete, CommandType.Text, transaction, commandTimeout);
              {{ParamAddForDelete("model")}}        
                      return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                  }

                  public static async ValueTask<int> UpsertAsync({{ctx.DtoTypeName}} model, NpgsqlConnection connection, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                  {
                      if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);
                      await using var cmd = connection.CreateCommand(Pg_SqlUpsert, CommandType.Text, transaction, commandTimeout);
              {{ParamAdd("model")}}        
                      return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                  }
    
                  public static async ValueTask<int> TruncateAsync(NpgsqlConnection connection, CancellationToken ct, NpgsqlTransaction? transaction = null, int? commandTimeout = null)
                  {
                      if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct).ConfigureAwait(false);
                      await using var cmd = connection.CreateCommand(Pg_SqlTruncate, CommandType.Text, transaction, commandTimeout);
                      return await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
                  }
              }
              """";

        spc.AddSource($"{dto.Name}.Domain.Npgsql.g.cs", src);
        return;

        string ParamAdd(string modelName)
        {
            var sb = new StringBuilder();
            foreach (var col in ctx.Columns)
                sb.AppendLine($"        cmd.Parameters.Add({dto.Name}Npgsql.CreateParameter{col.Name}({modelName}.{col.Name}));");
            return sb.ToString();
        }

        string ParamAddForUpdate(string modelName)
        {
            var sb = new StringBuilder();
            foreach (var col in ctx.NonKeyNonIdentities)
                sb.AppendLine($"        cmd.Parameters.Add({dto.Name}Npgsql.CreateParameter{col.Name}({modelName}.{col.Name}));");
            foreach (var col in ctx.Keys)
                sb.AppendLine($"        cmd.Parameters.Add({dto.Name}Npgsql.CreateParameter{col.Name}({modelName}.{col.Name}));");
            return sb.ToString();
        }

        string ParamAddForDelete(string modelName)
        {
            var sb = new StringBuilder();
            foreach (var col in ctx.Keys)
                sb.AppendLine($"        cmd.Parameters.Add({dto.Name}Npgsql.CreateParameter{col.Name}({modelName}.{col.Name}));");
            return sb.ToString();
        }

        string ParamAddBatchFlat(string modelName, string indexName)
        {
            var sb = new StringBuilder();
            foreach (var col in ctx.NonIdentities)
            {
                sb.AppendLine($"            cmd.Parameters.Add({dto.Name}Npgsql.CreateParameter{col.Name}({modelName}.{col.Name}, $\"@p{{{indexName}}}\"));");
                sb.AppendLine($"            {indexName}++; ");
            }
            return sb.ToString();
        }
    }
}