using System.Linq;
using System.Text;
using AdoGen.Generator.Extensions;
using AdoGen.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.PostgreSql;

internal sealed class DtoMapperEmitterNpgSql : IEmitter
{
    private DtoMapperEmitterNpgSql() { }
    public static DtoMapperEmitterNpgSql Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider)
        => provider is SqlProviderKind.PostgreSql && kind >= SqlModelKind.Mapper;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        var accessibility = dto.DeclaredAccessibility.ToString().ToLowerInvariant();
        var dtoProps = profileInfo.DtoProperties;

        var setUsingConstructor = dto.Constructors.Any(x => x.Parameters.Length > 0);

        var ordinals = new StringBuilder();
        var init = new StringBuilder();
        var read = new StringBuilder();
        var constBuilder = new StringBuilder();
        var methodBuilder = new StringBuilder();
        var sep = setUsingConstructor ? ":" : "=";
        var needsEnumCastHelper = false;
        var fieldPrefix = "Pg_";

        if (setUsingConstructor) read.Append('(').AppendLine();
        else read.AppendLine("{");

        for (var i = 0; i < dtoProps.Length; i++)
        {
            var p = dtoProps[i];
            var cfg = profileInfo.ParamsByProperty[p.Name];
            var ordinalField = $"{fieldPrefix}{cfg.ParameterName}Ordinal";
            var isLast = i == dtoProps.Length - 1;
            var getterExpr = EmitReaderGet(p, ordinalField, out bool needsEnumCastForThis);

            if (needsEnumCastForThis) needsEnumCastHelper = true;
            
            ordinals.AppendLine($"    private static int {ordinalField};");
            init.AppendLine($"            {ordinalField} = reader.GetOrdinal(\"{cfg.ParameterName}\");");
            read.AppendLine($"            {cfg.PropertyName} {sep} {getterExpr}{(isLast ? "" : ",")}");
            constBuilder.AppendLine(CreateSqlParameterConst(cfg));
            methodBuilder.AppendLine(CreateNpgsqlParameterMethod(cfg));
        }

        read.Append(setUsingConstructor ? "        )" : "        }");

        var methods = methodBuilder.ToString().TrimEnd();
        var dtoTypeName = dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var typeKeyword = dto.IsRecord ? "record" : "class";
        var ns = profileInfo.Namespace;
        
        var isInitField = "Pg_IsInitialized";

        var src =
            $$"""
              // <auto-generated />
              using AdoGen.PostgreSql;
              using Npgsql;
              using NpgsqlTypes;
              using System.Runtime.CompilerServices;

              namespace {{ns}};

              {{accessibility}} sealed partial {{typeKeyword}} {{dto.Name}} : INpgsqlMapper<{{dtoTypeName}}>
              {
                  private static bool {{isInitField}};
              {{ordinals}}
                  public static {{dtoTypeName}} Map(NpgsqlDataReader reader)
                  {
                      if (!{{isInitField}})
                      {
              {{init}}
                          {{isInitField}} = true;
                      }

                      return new {{dtoTypeName}}{{read}};
                  }
              }
              
              /// <summary>
              /// Helper methods for creating typed PostgreSQL parameters for {{dto.Name}}.
              /// </summary>
              {{accessibility}} static class {{dto.Name}}Npgsql
              {
              {{constBuilder}}
              {{methods}}
              }
              """;
        
        spc.AddSource($"{dto.Name}.Mapper.Npgsql.g.cs", src);
    }

    private static string EmitReaderGet(
        IPropertySymbol p,
        string ordinalField,
        out bool needsEnumCastHelper)
    {
        var (underlying, isNullableValueType) = p.Type.UnwrapNullable();
        var isNullable = isNullableValueType || p.NullableAnnotation == NullableAnnotation.Annotated;
        var propertyTypeKey = p.Type.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat);
        var dbNullValueExpr = isNullableValueType ? $"({propertyTypeKey})null" : "null";
        
        if (underlying.TypeKind == TypeKind.Enum)
        {
            needsEnumCastHelper = true;
            var enumUnderlying = ((INamedTypeSymbol)underlying).EnumUnderlyingType!;

            var (eu, _) = enumUnderlying.UnwrapNullable();
            var coreGetterName = eu.SpecialType switch
            {
                SpecialType.System_SByte => "GetSByte",
                SpecialType.System_Byte => "GetByte",
                SpecialType.System_Int16 => "GetInt16",
                SpecialType.System_UInt16 => "GetInt16",
                SpecialType.System_Int32 => "GetInt32",
                SpecialType.System_UInt32 => "GetInt32",
                SpecialType.System_Int64 => "GetInt64",
                SpecialType.System_UInt64 => "GetInt64",
                _ => null
            };

            if (coreGetterName is not null)
            {
                var read = $"reader.{coreGetterName}({ordinalField})";
                var cast = $"({underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat)}){read}";
                return isNullable
                    ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {cast}"
                    : cast;
            }

            var enumKey = underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat);
            var fv = $"reader.GetFieldValue<{enumKey}>({ordinalField})";
            return isNullable ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {fv}" : fv;
        }
        
        needsEnumCastHelper = false;
        
        if (underlying.SpecialType == SpecialType.System_Char)
        {
            var readChar = $"reader.GetString({ordinalField})[0]";
            
            return isNullable
                ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {readChar}"
                : readChar;
        }

        var getter = underlying.SpecialType switch
        {
            SpecialType.System_Boolean => "GetBoolean",
            SpecialType.System_Byte => "GetByte",
            SpecialType.System_Int16 => "GetInt16",
            SpecialType.System_Int32 => "GetInt32",
            SpecialType.System_Int64 => "GetInt64",
            SpecialType.System_Single => "GetFloat",
            SpecialType.System_Double => "GetDouble",
            SpecialType.System_Decimal => "GetDecimal",
            SpecialType.System_String => "GetString",
            _ => underlying.ToDisplayString(RoslynSymbolExtensions.GetterKeyFormat) switch
            {
                "global::System.Guid" => "GetGuid",
                "global::System.DateTime" => "GetDateTime",
                var key => $"GetFieldValue<{key}>"
            }
        };

        getter = $"reader.{getter}({ordinalField})";

        return isNullable ? $"reader.IsDBNull({ordinalField}) ? {dbNullValueExpr} : {getter}" : getter;
    }
    
    private static readonly SymbolDisplayFormat TypeDisplay = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                                  SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static string CreateSqlParameterConst(ParamConfig cfg)
        => $"""    public const string Parameter{cfg.PropertyName} = "{cfg.ParameterName}";""";

    private static string CreateNpgsqlParameterMethod(ParamConfig cfg)
    {
        var methodName = $"CreateParameter{cfg.PropertyName}";
        var constName = $"Parameter{cfg.PropertyName}";
        var typeName = cfg.PropertyType.ToDisplayString(TypeDisplay);

        var isNullableValueType = cfg.PropertyType is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };

        // Npgsql cannot write .NET enum types directly when NpgsqlDbType is set to an integer type.
        // We must cast enum values to their underlying primitive type.
        var enumCast = ResolveNpgsqlEnumCast(cfg.PropertyType);
        string valueExpr;
        if (enumCast is not null)
        {
            valueExpr = isNullableValueType || cfg.PropertyType.IsReferenceType
                ? $"value is null ? DBNull.Value : ({enumCast})value"
                : $"({enumCast})value";
        }
        else
        {
            valueExpr = cfg.PropertyType.IsReferenceType || isNullableValueType
                ? "value is null ? DBNull.Value : value"
                : "value";
        }

        var optional = new StringBuilder();
        if (cfg.Size is { } size) optional.AppendLine($"        Size = {size},");
        if (cfg.Precision is { } pr) optional.AppendLine($"        Precision = {pr},");
        if (cfg.Scale is { } sc) optional.AppendLine($"        Scale = {sc},");

        var optionalParams = optional.ToString().TrimEnd();

        return $$"""
                /// <summary>
                /// Creates an NpgsqlParameter with the configured db type and size/precision/scale.
                /// </summary>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static NpgsqlParameter {{methodName}}({{typeName}} value, string? propertyName = null) => new()
                {
                    ParameterName = propertyName ?? {{constName}},
                    NpgsqlDbType = NpgsqlDbType.{{cfg.DbType!.Value.EnumMember}},
                    Value = {{valueExpr}},{{(string.IsNullOrEmpty(optionalParams) ? "" : "\n" + optionalParams)}}
                };
                
            """;
    }
    
    /// <summary>
    /// Returns the C# cast expression for enum types (e.g. "(int)") or null if no cast is needed.
    /// Npgsql requires enum values to be written as their underlying primitive type.
    /// </summary>
    private static string? ResolveNpgsqlEnumCast(ITypeSymbol type)
    {
        var (underlying, _) = type.UnwrapNullable();
        if (underlying.TypeKind != TypeKind.Enum || underlying is not INamedTypeSymbol enumType)
            return null;

        return enumType.EnumUnderlyingType?.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int32 => "int",
            SpecialType.System_UInt32 => "uint",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            _ => "int"
        };
    }
}