using System.Linq;
using System.Text;
using AdoGen.Generator.Extensions;
using AdoGen.Generator.Models;
using AdoGen.Generator.Pipelines;
using Microsoft.CodeAnalysis;

namespace AdoGen.Generator.Emitters.PostgreSql;

internal sealed class ParameterHelpersEmitterNpgSql : IEmitter
{
    private ParameterHelpersEmitterNpgSql() { }
    public static ParameterHelpersEmitterNpgSql Instance { get; } = new();
    
    public bool IsMatch(SqlModelKind kind, SqlProviderKind provider) =>
        provider is SqlProviderKind.PostgreSql && kind >= SqlModelKind.Result;

    public void Handle(SourceProductionContext spc, ValidatedDiscoveryDto validatedDto)
    {
        var (discoveryDto, profileInfo, _) = validatedDto;
        var dto = discoveryDto.Dto;
        
                var constBuilder = new StringBuilder();
        var methodBuilder = new StringBuilder();

        var paramConfigs = profileInfo.ParamsByProperty.Select(x => x.Value).OrderBy(x => x.PropertyName);
        foreach (var kvp in paramConfigs)
        {
            constBuilder.AppendLine(CreateSqlParameterConst(kvp));
            methodBuilder.AppendLine(CreateNpgsqlParameterMethod(kvp));
            methodBuilder.AppendLine();
        }
        
        var methods = methodBuilder.ToString().TrimEnd();

        var src = 
            $$"""
            // <auto-generated />
            #nullable enable
            using System;
            using System.Runtime.CompilerServices;
            using Npgsql;
            using NpgsqlTypes;

            namespace AdoGen.PostgreSql;

            /// <summary>
            /// Helper methods for creating typed PostgreSQL parameters for {{dto.Name}}.
            /// </summary>
            public static class {{dto.Name}}Npgsql
            {
            {{constBuilder}}
            {{methods}}
            }
            """;

        spc.AddSource($"{dto.Name}.Npgsql.g.cs", src);
    }

    private static readonly SymbolDisplayFormat TypeDisplay = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                                  SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static string CreateSqlParameterConst(ParamConfig cfg)
        => $"""    public const string Parameter{cfg.PropertyName} = "{cfg.ParameterName}";""";

    private static string CreateNpgsqlParameterMethod(ParamConfig cfg)
    {
        var methodName = $"CreateParameter{cfg.PropertyName}";
        var constName = $"Parameter{cfg.PropertyName}";
        var typeName = cfg.PropertyType.ToDisplayString(TypeDisplay);

        var isNullableValueType = cfg.PropertyType is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };

        // Npgsql cannot write .NET enum types directly when NpgsqlDbType is set to an integer type.
        // We must cast enum values to their underlying primitive type.
        var enumCast = ResolveNpgsqlEnumCast(cfg.PropertyType);
        string valueExpr;
        if (enumCast is not null)
        {
            valueExpr = isNullableValueType || cfg.PropertyType.IsReferenceType
                ? $"value is null ? DBNull.Value : ({enumCast})value"
                : $"({enumCast})value";
        }
        else
        {
            valueExpr = cfg.PropertyType.IsReferenceType || isNullableValueType
                ? "value is null ? DBNull.Value : value"
                : "value";
        }

        var optional = new StringBuilder();
        if (cfg.Size is { } size) optional.AppendLine($"        Size = {size},");
        if (cfg.Precision is { } pr) optional.AppendLine($"        Precision = {pr},");
        if (cfg.Scale is { } sc) optional.AppendLine($"        Scale = {sc},");

        var optionalParams = optional.ToString().TrimEnd();

        return $$"""
                /// <summary>
                /// Creates an NpgsqlParameter with the configured db type and size/precision/scale.
                /// </summary>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static NpgsqlParameter {{methodName}}({{typeName}} value, string? propertyName = null) => new()
                {
                    ParameterName = propertyName ?? {{constName}},
                    NpgsqlDbType = NpgsqlDbType.{{cfg.DbType!.Value.EnumMember}},
                    Value = {{valueExpr}},{{(string.IsNullOrEmpty(optionalParams) ? "" : "\n" + optionalParams)}}
                };
            """;
    }

    /// <summary>
    /// Returns the C# cast expression for enum types (e.g. "(int)") or null if no cast is needed.
    /// Npgsql requires enum values to be written as their underlying primitive type.
    /// </summary>
    private static string? ResolveNpgsqlEnumCast(ITypeSymbol type)
    {
        var (underlying, _) = type.UnwrapNullable();
        if (underlying.TypeKind != TypeKind.Enum || underlying is not INamedTypeSymbol enumType)
            return null;

        return enumType.EnumUnderlyingType?.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int32 => "int",
            SpecialType.System_UInt32 => "uint",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            _ => "int"
        };
    }
}