using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using AdoGen.Generator.Models;

namespace AdoGen.Generator.Emitters.PostgreSql;

/// <summary>
/// Pure SQL string production for PostgreSQL. All methods are stateless and testable
/// with hand-built EmitContext fixtures — no Roslyn compilation required.
/// </summary>
internal static class PostgreSqlSqlTextBuilder
{
    public static string CreateTable(EmitContext ctx)
    {
        var sbColDefs = new StringBuilder();
        
        for (var i = 0; i < ctx.Columns.Length; i++)
        {
            var col = ctx.Columns[i];
            var nullability = col.IsNullable ? "NULL" : "NOT NULL";
            var identity = col.IsIdentity ? " GENERATED BY DEFAULT AS IDENTITY" : "";
            var defaultClause = col.DefaultSqlExpression is not null ? $" {col.DefaultSqlExpression}" : "";
            var comma = i == ctx.Columns.Length - 1 ? "" : ",";
            sbColDefs.AppendLine($"        {col.ColumnNameQuoted} {col.SqlType}{identity}{defaultClause} {nullability}{comma}");
        }

        if (ctx.Keys.Length > 0)
        {
            var pkCols = BuildJoined(ctx.Keys, col => col.ColumnNameQuoted);
            sbColDefs.AppendLine($"    ,CONSTRAINT \"PK_{ctx.Profile.Table}\" PRIMARY KEY ({pkCols})");
        }

        var colDefs = sbColDefs.ToString().TrimEnd();
        
        return $"""
                 CREATE TABLE IF NOT EXISTS {ctx.SchemaTableQuoted}(
             {colDefs});
             """;
    }

    public static string Insert(EmitContext ctx)
    {
        var insertCols = BuildJoined(ctx.Writables, col => col.ColumnNameQuoted);
        var insertParams = BuildJoined(ctx.Writables, col => "@" + col.ParameterName);
        return $"INSERT INTO {ctx.SchemaTableQuoted} ({insertCols}) VALUES ({insertParams});";
    }

    /// <summary>
    /// Returns INSERT … VALUES (…) RETURNING * — populates all columns including server-generated ones.
    /// </summary>
    public static string InsertAndReturn(EmitContext ctx)
    {
        var insertCols = BuildJoined(ctx.Writables, col => col.ColumnNameQuoted);
        var insertParams = BuildJoined(ctx.Writables, col => "@" + col.ParameterName);
        return $"INSERT INTO {ctx.SchemaTableQuoted} ({insertCols}) VALUES ({insertParams}) RETURNING *;";
    }

    public static string InsertBatchPrefix(EmitContext ctx)
    {
        var insertCols = BuildJoined(ctx.Writables, col => col.ColumnNameQuoted);
        return $"INSERT INTO {ctx.SchemaTableQuoted} ({insertCols}) VALUES";
    }

    public static string Update(EmitContext ctx)
    {
        var updateSet = BuildJoined(ctx.WritableNonKeyNonIdentities, col => $"{col.ColumnNameQuoted} = @{col.ParameterName}");
        if (ctx.ConcurrencyToken is { } token)
        {
            var tokenBump = IsIntOrLong(token.PropertyType)
                ? $"{token.ColumnNameQuoted} = @{token.ParameterName} + 1"
                : $"{token.ColumnNameQuoted} = gen_random_uuid()";
            return $"UPDATE {ctx.SchemaTableQuoted} SET {updateSet}, {tokenBump} WHERE {ctx.WhereByKey} AND {token.ColumnNameQuoted} = @{token.ParameterName};";
        }
        return $"UPDATE {ctx.SchemaTableQuoted} SET {updateSet} WHERE {ctx.WhereByKey};";
    }

    public static string Delete(EmitContext ctx)
    {
        var tokenClause = ctx.ConcurrencyToken is { } token
            ? $" AND {token.ColumnNameQuoted} = @{token.ParameterName}"
            : "";
        return $"DELETE FROM {ctx.SchemaTableQuoted} WHERE {ctx.WhereByKey}{tokenClause};";
    }

    public static string Upsert(EmitContext ctx)
    {
        var insertSql = Insert(ctx).TrimEnd(';');
        var nonIdentityKeys = FilterNonIdentityKeys(ctx.Keys);
        var conflictKeys = BuildJoined(nonIdentityKeys, col => col.ColumnNameQuoted);
        var updateSetOnConflict = BuildJoined(ctx.WritableNonKeyNonIdentities,
            col => $"{col.ColumnNameQuoted} = EXCLUDED.{col.ColumnNameQuoted}");
        return $"{insertSql} ON CONFLICT ({conflictKeys}) DO UPDATE SET {updateSetOnConflict};";
    }

    public static string Truncate(EmitContext ctx) => $"TRUNCATE TABLE {ctx.SchemaTableQuoted};";

    /// <summary>
    /// Returns a SELECT 1 FROM … WHERE pk1 = @pk1 [AND pk2 = @pk2] LIMIT 1 statement.
    /// LIMIT 1 ensures the engine stops scanning after the first matching row.
    /// </summary>
    public static string Exists(EmitContext ctx)
        => $"SELECT 1 FROM {ctx.SchemaTableQuoted} WHERE {ctx.WhereByKey} LIMIT 1;";

    public static string DeleteBatchTemplate(EmitContext ctx, string keyName)
        => $"DELETE FROM {ctx.SchemaTableQuoted} WHERE \"{keyName}\" IN (";

    /// <summary>
    /// Returns a DELETE … WHERE "keyCol" = ANY(@ids) statement for single-key batch delete.
    /// Passes all ids as a single typed array parameter — no per-row dynamic SQL building.
    /// </summary>
    public static string DeleteBatchAny(EmitContext ctx, string keyName)
        => $"DELETE FROM {ctx.SchemaTableQuoted} WHERE \"{keyName}\" = ANY(@ids);";

    /// <summary>
    /// Returns a DELETE … USING unnest(@k1s, @k2s) AS k(k1, k2) WHERE k.k1 = t.k1 AND k.k2 = t.k2 statement
    /// for composite-key batch delete. Uses a lateral join so the planner can apply index lookups per row.
    /// Each key gets its own array parameter named @{ParameterName}s.
    /// </summary>
    public static string DeleteBatchUnnest(EmitContext ctx)
    {
        var unnestArgs = BuildJoined(ctx.Keys, col => $"@{col.ParameterName}s");
        var aliasCols = BuildJoined(ctx.Keys, col => $"\"{col.ParameterName}\"");
        var whereClauses = BuildJoined(ctx.Keys, col => $"k.\"{col.ParameterName}\" = t.{col.ColumnNameQuoted}", " AND ");
        return $"DELETE FROM {ctx.SchemaTableQuoted} AS t USING unnest({unnestArgs}) AS k({aliasCols}) WHERE {whereClauses};";
    }

    /// <summary>
    /// Returns the static prefix of the DELETE…USING(VALUES…) statement for single-key batch delete.
    /// e.g. "DELETE FROM "public"."Users" AS t USING (VALUES "
    /// </summary>
    public static string DeleteBatchJoinValuesPrefix(EmitContext ctx)
        => $"DELETE FROM {ctx.SchemaTableQuoted} AS t USING (VALUES ";

    /// <summary>
    /// Returns the closing " AS ids(...) WHERE ..." fragment appended after all value rows.
    /// Works for both single and composite keys.
    /// </summary>
    public static string DeleteBatchJoinValuesSuffix(EmitContext ctx)
    {
        var aliasCols = BuildJoined(ctx.Keys, col => col.ColumnNameQuoted);
        var whereClauses = BuildJoined(ctx.Keys, col => $"ids.{col.ColumnNameQuoted}=t.{col.ColumnNameQuoted}", " AND ");
        return $") AS ids({aliasCols}) WHERE {whereClauses}";
    }

    public static string BulkCreateTempTable(EmitContext ctx, string tempTableName)
    {
        var sbColDefs = new StringBuilder();
        for (var i = 0; i < ctx.BulkColumns.Length; i++)
        {
            var col = ctx.BulkColumns[i];
            var nullability = col.IsNullable ? "NULL" : "NOT NULL";
            sbColDefs.AppendLine($"    \"{col.ParameterName}\" {col.SqlType} {nullability},");
        }
        sbColDefs.Append("    \"operation\" CHAR(1) NOT NULL");

        return $"""
                CREATE TEMP TABLE IF NOT EXISTS "{tempTableName}"(
                {sbColDefs});
                """;
    }

    /// <summary>
    /// Returns the CREATE INDEX statement to run after data is loaded into the temp table.
    /// UNIQUE only when all key columns are non-identity — identity keys have a placeholder value
    /// during 'I' rows so uniqueness across (operation, key) cannot be guaranteed.
    /// No IF NOT EXISTS — the temp table is always freshly created.
    /// </summary>
    public static string BulkCreateIndex(EmitContext ctx, string tempTableName)
    {
        var keyCols = BuildJoined(ctx.Keys, col => $"\"{col.ParameterName}\"");
        var hasIdentityKey = false;
        for (var i = 0; i < ctx.Keys.Length; i++)
            if (ctx.Keys[i].IsIdentity) { hasIdentityKey = true; break; }
        var unique = hasIdentityKey ? "" : "UNIQUE ";
        var idxPrefix = hasIdentityKey ? "ix" : "uix";
        var idxName = $"{idxPrefix}_{tempTableName}_op_keys";
        return $"CREATE {unique}INDEX \"{idxName}\" ON \"{tempTableName}\" (\"operation\", {keyCols});";
    }

    /// <summary>
    /// Returns the ANALYZE statement for the temp table — useful when rowCount >= 1000
    /// to give the planner accurate statistics before the DML statements run.
    /// </summary>
    public static string BulkAnalyze(string tempTableName)
        => $"ANALYZE \"{tempTableName}\";";

    /// <summary>
    /// Generates individual DML SQL statements for sequential execution.
    /// Each statement is a standalone UPDATE/INSERT/DELETE that the runtime executes
    /// via ExecuteNonQueryAsync, collecting affected row counts independently.
    /// Avoids the single large data-modifying CTE pattern which hits PostgreSQL
    /// restrictions when multiple CTEs touch the same target table.
    /// </summary>
    public static BulkApplyStatements BulkApply(EmitContext ctx, string tempTableName, string schemaTable)
    {
        var joinOn = ctx.JoinOn;
        var tempTableRef = $"\"{tempTableName}\"";
        var insertCols = BuildJoined(ctx.Writables, col => col.ColumnNameQuoted);
        var insertSelect = BuildJoined(ctx.Writables, col => $"S.{col.ColumnNameQuoted}");

        var updateSet = string.Join(",\n    ", Enumerable.Select(ctx.WritableNonKeyNonIdentities,
            col => $"    \"{col.ParameterName}\" = S.\"{col.ParameterName}\""));

        var nonIdentityKeys = FilterNonIdentityKeys(ctx.Keys);
        var conflictKeys = BuildJoined(nonIdentityKeys, col => col.ColumnNameQuoted);

        // U: update existing rows
        string? updateU = null;
        if (ctx.WritableNonKeyNonIdentities.Length > 0)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"UPDATE {schemaTable} AS T");
            sb.AppendLine("    SET " + updateSet.TrimStart());
            sb.AppendLine($"FROM {tempTableRef} AS S");
            sb.Append($"WHERE S.\"operation\" = 'U' AND {joinOn}");
            updateU = sb.ToString();
        }

        // I: insert new rows; let unique constraint violations fail naturally
        string? insertI = null;
        if (ctx.Writables.Length > 0)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"INSERT INTO {schemaTable} ({insertCols})");
            sb.AppendLine($"    SELECT {insertSelect}");
            sb.AppendLine($"    FROM {tempTableRef} AS S");
            sb.Append("    WHERE S.\"operation\" = 'I'");
            insertI = sb.ToString();
        }

        // D: delete existing rows
        var sb2 = new StringBuilder();
        sb2.AppendLine($"DELETE FROM {schemaTable} AS T");
        sb2.AppendLine($"USING {tempTableRef} AS S");
        sb2.Append($"WHERE S.\"operation\" = 'D' AND {joinOn}");
        var deleteD = sb2.ToString();

        // M update: update existing rows (counted into Updated)
        string? updateM = null;
        if (ctx.WritableNonKeyNonIdentities.Length > 0)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"UPDATE {schemaTable} AS T");
            sb.AppendLine("    SET " + updateSet.TrimStart());
            sb.AppendLine($"FROM {tempTableRef} AS S");
            sb.Append($"WHERE S.\"operation\" = 'M' AND {joinOn}");
            updateM = sb.ToString();
        }

        // M insert-missing: only rows not matched by M-update above, using ON CONFLICT DO NOTHING
        string? insertM = null;
        if (ctx.Writables.Length > 0 && conflictKeys.Length > 0)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"INSERT INTO {schemaTable} ({insertCols})");
            sb.AppendLine($"    SELECT {insertSelect}");
            sb.AppendLine($"    FROM {tempTableRef} AS S");
            sb.AppendLine("    WHERE S.\"operation\" = 'M'");
            sb.Append($"ON CONFLICT ({conflictKeys}) DO NOTHING");
            insertM = sb.ToString();
        }

        return new BulkApplyStatements(updateU, insertI, deleteD, updateM, insertM);
    }

    private static bool IsIntOrLong(string propertyType)
        => propertyType is "int" or "long" or "global::System.Int32" or "global::System.Int64";

    private static ImmutableArray<ColumnInfo> FilterNonIdentityKeys(ImmutableArray<ColumnInfo> keys)
    {
        var builder = ImmutableArray.CreateBuilder<ColumnInfo>(keys.Length);
        
        for (var i = 0; i < keys.Length; i++) if (!keys[i].IsIdentity) builder.Add(keys[i]);
        
        return builder.ToImmutable();
    }

    private static string BuildJoined(ImmutableArray<ColumnInfo> columns, Func<ColumnInfo, string> selector, string separator = ", ")
    {
        if (columns.Length == 0) return string.Empty;
        if (columns.Length == 1) return selector(columns[0]);
        
        var sb = new StringBuilder(columns.Length * 24);
        
        for (var i = 0; i < columns.Length; i++)
        {
            if (i > 0) sb.Append(separator);
            sb.Append(selector(columns[i]));
        }
        
        return sb.ToString();
    }
}

/// <summary>
/// Holds the individual DML SQL statements for the PostgreSQL bulk apply operation.
/// Each non-null string is executed sequentially via ExecuteNonQueryAsync.
/// Null entries indicate the operation is not applicable for this DTO's shape.
/// </summary>
/// <param name="UpdateU">UPDATE for 'U' operation rows — null when no non-key writable columns.</param>
/// <param name="InsertI">INSERT for 'I' operation rows — null when no writable columns.</param>
/// <param name="DeleteD">DELETE for 'D' operation rows — always present.</param>
/// <param name="UpdateM">UPDATE for 'M' operation rows (upsert update pass) — null when no non-key writable columns.</param>
/// <param name="InsertM">INSERT for 'M' operation rows (upsert insert-missing pass) — null when no writable columns or no conflict keys.</param>
internal readonly record struct BulkApplyStatements(
    string? UpdateU,
    string? InsertI,
    string DeleteD,
    string? UpdateM,
    string? InsertM);

